
language: python
python:
  # - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.5-dev" # 3.5 development branch
  - "pypy"
# command to install dependencies
# cache:
#   directories:
#     - $HOME/.cache/pip
install: 
- "echo '\nconfig interactive 0' >> .compmake.rc "
- "pip install -r requirements.txt"
- dot -V
- "if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install matplotlib ; fi"
- "if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then python -c 'import matplotlib' ; fi"
- python setup.py develop
# command to run tests
script: 
- make comptests-run-parallel
after_failure:
- compmake out/comptests -c "ls failed"
- compmake out/comptests -c "why failed"
- cat emergency.dot
addons:
  apt:
    # sources:
    # - ubuntu-toolchain-r-test
    packages:
    - python-matplotlib
    - python-numpy
    - python-yaml
    # - python-cjson disallowed by Travis!
    # - python-pil not found on Travis
    - graphviz # TODO: add check for existence
