
- id: single
  desc: Single element
  code:
  - mocdp.posets.Single
  - element: "*"

- id: interval01
  desc: Test interval
  code:
  - mocdp.posets.Interval
  - L: 0.0
    U: 1.0

- id: Rcomp
  desc: "[0, ...] U [infinity]"
  code:
  - mocdp.posets.Rcomp
  - {}

- id: Rcomp_g
  desc: grams
  code:
  - mocdp.posets.RcompUnits
  - units: g

- id: Rcomp_J
  desc: Joules
  code:
  - mocdp.posets.RcompUnits
  - units: J

- id: U_Rcomp
  desc: upper sets of Rcomp
  code:
  - mocdp.posets.UpperSets
  - P: 'Rcomp'

- id: U_interval01
  desc: upper sets of interval
  code:
  - mocdp.posets.UpperSets
  - P: 'interval01'

- id: square
  desc: "[0,1]x[0,1]"
  code:
  - mocdp.posets.PosetProduct
  - subs: 
    - interval01
    - interval01



